### ISSUE TITLE
With pyinstaller No such file or directory: '/tmp/_MEIvFqLAS/xmlschema/validators/schemas/XSD_1.0/XMLSchema.xsd'

### ISSUE THREAD

**Issue by paolodina** [brunato/xmlschema#100]
Hi Davide and thanks for the useful library, first I'm not sure it's an xmlschema issue. Trying using pyinstaller to generate a single executable the file is generated, but running it I get an exception. I'm importing xmlschema with `import xmlschema`. Commenting this line everything works (though without xmlschema ;-).

```
Traceback (most recent call last):
  File "urllib/request.py", line 1339, in open_local_file
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIvFqLAS/xmlschema/validators/schemas/XSD_1.0/XMLSchema.xsd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xmlschema/validators/schema.py", line 235, in __init__
  File "xmlschema/resources.py", line 238, in __init__
  File "xmlschema/resources.py", line 262, in __setattr__
  File "xmlschema/resources.py", line 340, in _fromsource
  File "urllib/request.py", line 161, in urlopen
  File "urllib/request.py", line 464, in open
  File "urllib/request.py", line 482, in _open
  File "urllib/request.py", line 442, in _call_chain
  File "urllib/request.py", line 1317, in file_open
  File "urllib/request.py", line 1357, in open_local_file
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/tmp/_MEIvFqLAS/xmlschema/validators/schemas/XSD_1.0/XMLSchema.xsd'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui.py", line 2, in <module>
    from app import convert, loader
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "/home/paolo/devel/lavoro/sel/2019_regione_xls_xml/venv/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "app/convert.py", line 1, in <module>
    import xmlschema
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "/home/paolo/devel/lavoro/sel/2019_regione_xls_xml/venv/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "xmlschema/__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "/home/paolo/devel/lavoro/sel/2019_regione_xls_xml/venv/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "xmlschema/documents.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "/home/paolo/devel/lavoro/sel/2019_regione_xls_xml/venv/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "xmlschema/validators/__init__.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "/home/paolo/devel/lavoro/sel/2019_regione_xls_xml/venv/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "xmlschema/validators/schema.py", line 895, in <module>
  File "xmlschema/validators/schema.py", line 130, in __new__
  File "xmlschema/validators/schema.py", line 237, in __init__
urllib.error.URLError: <urlopen error cannot create schema: <urlopen error [Errno 2] No such file or directory: '/tmp/_MEIvFqLAS/xmlschema/validators/schemas/XSD_1.0/XMLSchema.xsd'>>
[7729] Failed to execute script gui
```

My pip freeze:
```
altgraph==0.16.1
defusedxml==0.5.0
elementpath==1.1.2
et-xmlfile==1.0.1
future==0.17.1
generateDS==2.30.11
jdcal==1.4
lxml==4.3.0
macholib==1.11
openpyxl==2.5.14
pefile==2018.8.8
PyInstaller==3.4
PySimpleGUI==3.24.0
six==1.12.0
xmlschema==1.0.8
```

**Comment by brunato** [comment]
Maybe ``setuptools`` missing.

**Comment by paolodina** [comment]
Thanks, it was a packaging issue on my side. For reference...

```
pyinstaller \
    --add-data=./venv/lib/python3.4/site-packages/xmlschema/validators/schemas/XSD_1.0/XMLSchema.xsd:./xmlschema/validators/schemas/XSD_1.0/ \
    --add-data=./venv/lib/python3.4/site-packages/xmlschema/validators/schemas/XSD_1.1/XMLSchema.xsd:./xmlschema/validators/schemas/XSD_1.1/ \
    --add-data=./venv/lib/python3.4/site-packages/xmlschema/validators/schemas/XSD_1.1/list_builtins.xsd:./xmlschema/validators/schemas/XSD_1.1/ \
    --add-data=./venv/lib/python3.4/site-packages/xmlschema/validators/schemas/xml_minimal.xsd:./xmlschema/validators/schemas \
    --add-data=./venv/lib/python3.4/site-packages/xmlschema/validators/schemas/xlink.xsd:./xmlschema/validators/schemas \
    --add-data=./venv/lib/python3.4/site-packages/xmlschema/validators/schemas/XMLSchema-hasFacetAndProperty_minimal.xsd:./xmlschema/validators/schemas \
    --add-data=./venv/lib/python3.4/site-packages/xmlschema/validators/schemas/XMLSchema-instance_minimal.xsd:./xmlschema/validators/schemas \
    -wF gui.py
```
