### ISSUE TITLE
dateTime with microseconds problem

### ISSUE THREAD

**Issue by novoxudonoser** [brunato/xmlschema#15]
Hello. I have a problem with deserializing microseconds in datetime 
```>>> xs.to_dict('searchFlights')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/xsdbase.py", line 281, in decode
    for chunk in self.iter_decode(data, validation=validation, *args, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/schema.py", line 417, in iter_decode
    decimal_type=decimal_type, element_decode_hook=element_decode_hook):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/elements.py", line 239, in iter_decode
    for result in self.type.iter_decode(elem, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/complex_types.py", line 426, in iter_decode
    for result in self.content_type.iter_decode(elem, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/groups.py", line 294, in iter_decode
    for result in xsd_element.iter_decode(child, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/elements.py", line 239, in iter_decode
    for result in self.type.iter_decode(elem, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/complex_types.py", line 426, in iter_decode
    for result in self.content_type.iter_decode(elem, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/groups.py", line 294, in iter_decode
    for result in xsd_element.iter_decode(child, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/elements.py", line 239, in iter_decode
    for result in self.type.iter_decode(elem, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/complex_types.py", line 426, in iter_decode
    for result in self.content_type.iter_decode(elem, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/groups.py", line 294, in iter_decode
    for result in xsd_element.iter_decode(child, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/elements.py", line 239, in iter_decode
    for result in self.type.iter_decode(elem, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/complex_types.py", line 426, in iter_decode
    for result in self.content_type.iter_decode(elem, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/groups.py", line 294, in iter_decode
    for result in xsd_element.iter_decode(child, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/elements.py", line 239, in iter_decode
    for result in self.type.iter_decode(elem, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/complex_types.py", line 426, in iter_decode
    for result in self.content_type.iter_decode(elem, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/groups.py", line 294, in iter_decode
    for result in xsd_element.iter_decode(child, validation, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/components/elements.py", line 280, in iter_decode
    raise result
xmlschema.exceptions.XMLSchemaValidationError: failed validating u'2017-09-06T23:59:00.000' with <function non_negative_int_validator at 0x7f046e7b6398>.

Reason: invalid datetime for format '%Y-%m-%dT%H:%M:%S'.

Schema:

    <xs:element xmlns:xs="http://www.w3.org/2001/XMLSchema" name="lastTicketDateTime" type="xs:dateTime" />

Instance:

    <lastTicketDateTime>2017-09-06T23:59:00.000+03:00</lastTicketDateTime>
```

**Comment by brunato** [comment]
This needs a check of builtins definition (`xmlschema/components/builtins.py`). I'll try to fix this for the next version, previewed for the second half of september.

**Comment by brunato** [comment]
Release 0.9.12 available on PyPI, this bug should be fixed (despite this the datetime builtins requires some improvements to parse all XSD specification, because the Python library is not so extended in date parsing).

**Comment by Kilte** [comment]
> Python library is not so extended in date parsing
You can try dateutil: https://dateutil.readthedocs.io/en/stable/parser.html

**Comment by brunato** [comment]
The needs for XSD date and time parsing are nearly the same of the standard `datetime` module, with some restrictions and very limited additions (eg. '-' before a date) . 

So I've decided to develop some tiny validator functions, one for each XSD datetime type. These validators seems working pretty well in version 0.9.14, available from today.

Bye

Davide
