### ISSUE TITLE
Support for namespace="##other"

### ISSUE THREAD

**Issue by candlerb** [brunato/xmlschema#38]
xmlschema does not appear to correctly support `namespace="##other"`, e.g.

~~~
        <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
~~~

which allows arbitrary other elements but only in a *different* namespace.

To reproduce, take the schema file `ala_1.0.xsd` from inside [this zip file](http://www.niccstandards.org.uk/files/current/ND1651v1.1.1.zip?type=zip)

and use it to validate this document:

~~~
<macResponse xmlns="http://www.niccstandards.org.uk/ala_1.0.xsd">

  <message>
    <messageId>b68b2cf4-475e-11e1-a92e-fb2ff6467c99</messageId>
    <correlationId>bac72cfa-475e-11e1-a92e-fb2ff6467c99</correlationId>
    <sentAt>2012-01-20T18:30:43Z</sentAt>
  </message>

  <buyer>
    <buyerIdentifier>1234567890</buyerIdentifier>
  </buyer>

  <seller>
    <sellerIdentifier>1234567890</sellerIdentifier>
  </seller>

  <macAccepted>
    <mac>
      <macKey>2345432345345</macKey>
      <macValidUntil>2012-01-20T18:30:43Z</macValidUntil>
    </mac>
    <junk>should not be accepted</junk>
  </macAccepted>

</macResponse>
~~~

The `<junk>` tag does not belong here, although `<ns0:junk>` would be OK if the namespace `ns0` were delcared.

xmlschema 0.9.18 wrongly accepts this document:

~~~
>>> import xmlschema
>>> my_schema = xmlschema.XMLSchema('ala_1.0.xsd')
>>> my_schema.validate("junk.xml")
>>>
~~~

But lxml correctly rejects it:

~~~
>>> from lxml import etree
>>> schema_root = etree.parse(open("ala_1.0.xsd"))
>>> schema = etree.XMLSchema(schema_root)
>>> parser = etree.XMLParser(schema=schema)
>>> etree.fromstring(open("junk.xml").read(), parser)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/lxml/etree.pyx", line 3227, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1752, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1066, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
  File "<string>", line 0
lxml.etree.XMLSyntaxError: Element '{http://www.niccstandards.org.uk/ala_1.0.xsd}junk': This element is not expected.
~~~

**Comment by brunato** [comment]
Ok, I'll check this with your sample.
Thanks
