### ISSUE TITLE
xmlschema fails to validate the xml with minOccurs=1 in certain scenarios

### ISSUE THREAD

**Issue by BangkokKid** [brunato/xmlschema#51]
First of all, @brunato , Thank you for making this project. This is really cool.

I am running into this issue and not sure if this is a bug or just simply my misunderstanding. Please see below. 

Here is my XML: 
```
<?xml version="1.0" encoding="UTF-8"?>
<KeyValuePairs>
	<test>root</test>
	<test2>root</test2>
	<test3>root</test3>
	<test4>root</test4>
	<test5>root</test5>
	<test6>root</test6>
	<test7>root</test7>
</KeyValuePairs>
```
Here is my XSD:
```
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

	<xs:element name="KeyValuePairs" type="KeyValuePairsType"/>
	<xs:complexType name="KeyValuePairsType">	
		<xs:all>
			<xs:element type="xs:string" name="test2" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test3" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test4" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test5" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test6" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test7" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test" minOccurs="1" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
</xs:schema>
```
I validated the xml using above schema, and I got the failure stating that it expects to see "test", but "test" element is actually present in the XML.   The strange part is if I move this line 
```"<xs:element type="xs:string" name="test" minOccurs="1" maxOccurs="1" />"``` up to the first on the list, the validation will pass. I am aware that ("minOccurs="1" maxOccurs="1" ) is redundant, but would like to explicitly use it.  The validation still fails if I remove them. 
If my understanding is correct the order of the <xs:element> should not matter, and order of the element should not matter in the xml with <xs:all>.  Please help.
```
BangkokKid@ubuntu:~/test/xmlschematest$ ./test.py 
xmlschema.__version__ is 0.9.22 
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    schema.validate("./data.xml")
  File "/usr/local/lib/python2.7/dist-packages/xmlschema/validators/xsdbase.py", line 406, in validate
    raise error
xmlschema.validators.exceptions.XMLSchemaChildrenValidationError: failed validating <Element 'KeyValuePairs' at 0x7f473ce34f90> with XsdGroup(model='all').

Reason: The content of element u'KeyValuePairs' is not complete. Tag u'test' expected.

Schema:

  <xs:all xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element maxOccurs="1" minOccurs="0" name="test2" type="xs:string" />
            <xs:element maxOccurs="1" minOccurs="0" name="test3" type="xs:string" />
            <xs:element maxOccurs="1" minOccurs="0" name="test4" type="xs:string" />
            <xs:element maxOccurs="1" minOccurs="0" name="test5" type="xs:string" />
            <xs:element maxOccurs="1" minOccurs="0" name="test6" type="xs:string" />
            <xs:element maxOccurs="1" minOccurs="0" name="test7" type="xs:string" />
            <xs:element maxOccurs="1" minOccurs="1" name="test" type="xs:string" />
  </xs:all>

Instance:

  <KeyValuePairs>
    <test2>root</test2>
    <test3>root</test3>
    <test4>root</test4>
    <test>root</test>
    <test5>root</test5>
    <test6>root</test6>
    <test7>root</test7>
  </KeyValuePairs>

```

**Comment by brunato** [comment]
It's a bug, I'm working on it. 
Thanks
Davide

**Comment by brunato** [comment]
The new version 0.9.23 resolve this issue (I've included a new test case for this). 

Best regards
Davide

**Comment by BangkokKid** [comment]
Just wanted to let you know that I got the 0.9.23, and it is working with this scenario now. I will try with the original xml and let you know if I run into any problem. Thanks for your help. 
```BangkokKid@ubuntu:~/test/xmlschematest$ ./test.py 
xmlschema.__version__ is 0.9.23 
True
```
