### ISSUE TITLE
Derivation from union and possible facets

### ISSUE THREAD

**Issue by vient** [brunato/xmlschema#67]
I stumbled upon rather weird example. Consider following schemas:
``` xml
<!-- microsoft-drawing-2010-main.xsd -->
<xsd:simpleType
 xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
 name="ST_SaturationAmount">
    <xsd:restriction base="a:ST_Percentage">
        <xsd:minInclusive value="0"/>
        <xsd:maxInclusive value="400000"/>
    </xsd:restriction>
</xsd:simpleType>

<!-- dml-main.xsd -->
<xsd:simpleType 
 xmlns:s="http://schemas.openxmlformats.org/officeDocument/2006/sharedTypes"
 name="ST_Percentage">
    <xsd:annotation>
        <xsd:documentation>Percentage</xsd:documentation>
    </xsd:annotation>
    <xsd:union memberTypes="ST_PercentageDecimal s:ST_Percentage"/>
</xsd:simpleType>
<xsd:simpleType
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 name="ST_PercentageDecimal">
    <xsd:annotation>
        <xsd:documentation>Percentage as Decimal Number</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:int"/>
</xsd:simpleType>

<!-- shared-commonSimpleTypes.xsd -->
<xsd:simpleType
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 name="ST_Percentage">
    <xsd:annotation>
        <xsd:documentation>Percentage Value with Sign</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="-?[0-9]+(\.[0-9]+)?%"/>
    </xsd:restriction>
</xsd:simpleType>
```

`ST_SaturationAmount` tries to derive by restriction an union datatype which consists of `xsd:int` and `xsd:string`. `xmlschema` fails to parse it with following error:
```
>>> q = xmlschema.XMLSchema("microsoft-drawing-2010-main.xsd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\schema.py", line 323, in __init__
    self.maps.build()
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\globals_.py", line 356, in build
    self.lookup_type(qname)
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\globals_.py", line 205, in lookup
    global_map[qname] = factory_or_class(elem, schema, is_global=True)
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 54, in xsd_simple_type_factory
    return XsdAtomicRestriction(child, schema, is_global=is_global, name=name)
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 312, in __init__
    """
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 77, in __init__
    super(XsdSimpleType, self).__init__(elem, schema, name, is_global)
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\xsdbase.py", line 150, in __init__
    self.elem = elem
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 819, in __setattr__
    {any attributes with non-schema namespace . . .}>
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 324, in __setattr__
    if name == 'base_type':
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 109, in __setattr__
    super(XsdSimpleType, self).__setattr__(name, value)
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\xsdbase.py", line 166, in __setattr__
    self._parse()
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 893, in _parse
    except KeyError:
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 819, in __setattr__
    {any attributes with non-schema namespace . . .}>
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 324, in __setattr__
    if name == 'base_type':
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 94, in __setattr__
    self._parse_error(err)
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\xsdbase.py", line 58, in _parse_error
    raise error
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 91, in __setattr__
    self.min_length, self.max_length, self.min_value, self.max_value = self.check_facets(value)
  File "C:\Program Files\Python36\lib\site-packages\xmlschema\validators\simple_types.py", line 163, in check_facets
    raise XMLSchemaParseError(msg % admitted_facets, self)
xmlschema.validators.exceptions.XMLSchemaParseError: one or more facets are not applicable, admitted set is {'enumeration', 'minLength', 'whiteSpace', 'pattern', 'length', 'maxLength'}:

  <xsd:restriction xmlns:xsd="http://www.w3.org/2001/XMLSchema" base="a:ST_Percentage">
            <xsd:minInclusive value="0" />
            <xsd:maxInclusive value="400000" />
  </xsd:restriction>
```

Looks like `xmlschema` tries to apply restriction to all base datatypes. Now, first I thought that maybe you only need to find the subset of base datatypes which you can apply restriction to, and apply it to them. Then I looked in the documentation and [it is actually said there](https://www.w3.org/TR/xmlschema-2/#derivation-by-union) that:
> As mentioned in Union datatypes (§2.5.1.3), when a datatype is ·derived· from a ·union· datatype, the only following ·constraining facet·s can be used:
·pattern·
·enumeration·
regardless of the ·constraining facet·s that are applicable to the datatypes that participate in the ·union·

Don't really know if it is a bug or not but it seems that here `xmlschema` is not conforming the documentation. I thought you may be interested in this information.

**Comment by brunato** [comment]
It is an error on `UNION_FACETS` in module _facets.py_ that remained for an oversight equals to `LIST_FACETS`. 

Now this set contains only _pattern_ and _enumeration_ (and also _assertion_ for XSD 1.1).
The fix is available with release 0.9.30.

Thanks for report me this incongruity.
