### ISSUE TITLE
AttributeError: 'XsdAnyElement' object has no attribute 'text'

### ISSUE THREAD

**Issue by Thomasb81** [brunato/xmlschema#74]
Hello

issue with 
xmlschema                          1.0.1
elementpath                        1.0.10

It look like elementpath library is not compatible with <any> Element class object: elementpath library seems to expect a text attribute.

```
[...]   
     for _descendant in _iter_descendants():
  File "/home/tom/.local/lib/python2.7/site-packages/elementpath/xpath_context.py", line 134, in _iter_descendants
    if elem.text is not None:
AttributeError: 'XsdAnyElement' object has no attribute 'text'
```
Schema files : http://www.accellera.org/xmlschema/spirit/1685-2009
test case (even if not so simple):
```
import xmlschema
my_schema = xmlschema.XMLSchema('component.xsd')
register = my_schema.find('//spirit:component')
```

**Comment by brunato** [comment]
It's correct that *elementpath* library expects a text attribute, instead it's necessary to apply the `ElementPathMixin` also to `XsdAnyElement` class and implement the missing methods.

Also I've also to fix schema elements iteration (`XsdElement.__iter__` method, rewritten similar to `XsdElement.iter`) to avoid infinite iterations.
Should be fixed in the next release.

Thanks

**Comment by Thomasb81** [comment]
Tanks Davide

I am able to load this schema without issue now. 

But the one provide in https://github.com/brunato/xmlschema/issues/20 is failing:

XMLSchemaValidationError: failed validating u'.//ipxact:parameter | .//ipxact:moduleParameter' with XsdPatternsFacet(['(\\.//)?(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.)(/(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.))*(\\|(\\.//)?(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.)(/(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.))*)*']).

Reason: value don't match any pattern of ['(\\.//)?(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.)(/(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.))*(\\|(\\.//)?(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.)(/(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.))*)*'].

Schema:

  <xs:pattern xmlns:xs="http://www.w3.org/2001/XMLSchema" value="(\.//)?(((child::)?((\i\c*:)?(\i\c*|\*)))|\.)(/(((child::)?((\i\c*:)?(\i\c*|\*)))|\.))*(\|(\.//)?(((child::)?((\i\c*:)?(\i\c*|\*)))|\.)(/(((child::)?((\i\c*:)?(\i\c*|\*)))|\.))*)*">
  </xs:pattern>

Instance:

    <xs:selector xmlns:xs="http://www.w3.org/2001/XMLSchema" xpath=".//ipxact:parameter | .//ipxact:moduleParameter" />

I use the same 3 lines script.

**Comment by Thomasb81** [comment]
One additionnal question on 1685_2009 schema (the one that is loading with version 1.0.2)

Is it possible to retrieve restriction data ? 

for example on following object :
my_schema.find("//spirit:register/spirit:access")
or
my_schema.find("//spirit:register/spirit:field/spirit:access")

I would expect to retrieve the following enumerate list of data :  "read-only", "write-only", "read-write", "writeOnce", "read-writeOnce" (MemoryMap.xsd) 

Thomas

**Comment by brunato** [comment]
Hi,
retrying with the schema of #20 my installation still works (I've download again the schema but it's also in my local tests collection):

```python
>>> import xmlschema
>>> xs = xmlschema.XMLSchema('1685-2014/component.xsd')
>>> xs.find('//ipxact:component')
XsdElement(name='ipxact:component')
>>> len(xs.findall('//ipxact:*'))
837
```
Check your installation for dependencies and if the error persists you could report me more information about Python version or error traceback.

About the second question generally a restriction can be found in `base_type` attribute of the element's `type`. But in those cases is not the restriction data that you have to access but the *facets* data that are stored in the `validators` attribute:

```python
>>> xs.find('//ipxact:register/ipxact:access').type.validators
[XsdEnumerationFacet(['read-only', 'write-only', 'read-write', 'writeOnce', 'read-writeOnce'])]
>>> xs.find('//ipxact:register/ipxact:field/ipxact:access').type.validators
[XsdEnumerationFacet(['read-only', 'write-only', 'read-write', 'writeOnce', 'read-writeOnce'])]
```

Davide

**Comment by Thomasb81** [comment]
Ok let me double check ...

**Comment by Thomasb81** [comment]
[test_case.py.tar.gz](https://github.com/brunato/xmlschema/files/2237767/test_case.py.tar.gz)
```

$python test_case.py 
Traceback (most recent call last):
  File "test_case.py", line 3, in <module>
    xs = xmlschema.XMLSchema('component.xsd')
  File "/home/tom/.local/lib/python2.7/site-packages/xmlschema/validators/schema.py", line 287, in __init__
    self.check_schema(root)
  File "/home/tom/.local/lib/python2.7/site-packages/xmlschema/validators/schema.py", line 489, in check_schema
    raise error
xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating u'.//ipxact:parameter | .//ipxact:moduleParameter' with XsdPatternsFacet(['(\\.//)?(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.)(/(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.))*(\\|(\\.//)?(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.)(/(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.))*)*']).

Reason: value don't match any pattern of ['(\\.//)?(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.)(/(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.))*(\\|(\\.//)?(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.)(/(((child::)?((\\i\\c*:)?(\\i\\c*|\\*)))|\\.))*)*'].

Schema:

  <xs:pattern xmlns:xs="http://www.w3.org/2001/XMLSchema" value="(\.//)?(((child::)?((\i\c*:)?(\i\c*|\*)))|\.)(/(((child::)?((\i\c*:)?(\i\c*|\*)))|\.))*(\|(\.//)?(((child::)?((\i\c*:)?(\i\c*|\*)))|\.)(/(((child::)?((\i\c*:)?(\i\c*|\*)))|\.))*)*">
  </xs:pattern>

Instance:

    <xs:selector xmlns:xs="http://www.w3.org/2001/XMLSchema" xpath=".//ipxact:parameter | .//ipxact:moduleParameter" />
```

**Comment by Thomasb81** [comment]
Also if reproduce your command on 1685-2009 version, I get empty list.

```
>>> import xmlschema
>>> xs = xmlschema('1685-2009/component.xsd')
>>> xs.find('//spirit:register/spirit:access').type.validators
[]
```

Thomas

**Comment by brunato** [comment]
I tried with python 2.7.15 on Linux platform and the 1685-2014 doesn't raise any error:

```python
$ python
Python 2.7.15 (default, May 16 2018, 17:50:09) 
[GCC 8.1.1 20180502 (Red Hat 8.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlschema
>>> xs = xmlschema.XMLSchema("component.xsd")
>>> 
```
Which 2.7 relase is installed in you case?

For the second question: in 1685-2009 the access elements use a restriction of *accessType*, so the validators are accessed from the `base_type`:

```python
>>> xs.find('//spirit:register/spirit:access').type.base_type.validators
[XsdEnumerationFacet(['read-only', 'write-only', 'read-write', 'writeOnce', 'read-writeOnce'])]
>>> xs.find('//spirit:register/spirit:field/spirit:access').type.base_type.validators
[XsdEnumerationFacet(['read-only', 'write-only', 'read-write', 'writeOnce', 'read-writeOnce'])]
```

Davide

**Comment by Thomasb81** [comment]
Very strange ...
I use the latest Ubuntu 18.04. which come with
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 

I try with python3.6 it was working. 

So I uninstall xmlschema _and_ elementpath then re-install xmlschema ...and it works now on my 2.7.15rc1.
uninstalling only xmlschema was not enough ... Look like this odd behavior was related to the pip automatic update of elementpath 1.0.10 to 1.0.11 ... 

Thomas

**Comment by Thomasb81** [comment]
I got the difference of the data structure between my two schema.  ... 
Thanks a lot.
Thomas

**Comment by brunato** [comment]
Model group information of a *complexType* are stored in the `content_type` attribute, that is the top-level group. In your case the choice subgroup is the 3rd item of this group, so:

```python
>>> view.type.content_type[2]
XsdGroup(model='choice')
>>> view.type.content_type[2][:]
[XsdElement(name='spirit:hierarchyRef'), XsdGroup(model='sequence')]
```

Davide
