### ISSUE TITLE
Problem concerning referential constraints in schema files

### ISSUE THREAD

**Issue by clarkgflipper** [brunato/xmlschema#87]
xmlschema throws an exeption when reading in an xsd file containing a referential constraint. To reproduce, import xmlschema and read in the xsd-file (see below). The schema file is appended. It works fine with XmlSpy.

Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlschema
>>> myxmlschema = xmlschema.XMLSchema("D:/Temp/mc/cdpedia2.xsd")
Traceback (most recent call last):
  File "D:\Users\BKU\BerndGuenther\AppData(Roaming)\Python\Python37\site-packages\xmlschema\validators\constraints.py", line 231, in parse_refer
    refer = self.parent.constraints[self.refer]
KeyError: 'unq_disk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\BKU\BerndGuenther\AppData(Roaming)\Python\Python37\site-packages\xmlschema\validators\schema.py", line 294, in __init__
    self.maps.build()
  File "D:\Users\BKU\BerndGuenther\AppData(Roaming)\Python\Python37\site-packages\xmlschema\validators\globals_.py", line 408, in build
    constraint.parse_refer()
  File "D:\Users\BKU\BerndGuenther\AppData(Roaming)\Python\Python37\site-packages\xmlschema\validators\constraints.py", line 240, in parse_refer
    xsd_element = refer.parent.parent
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'parent'
>>>
[cdpedia2.zip](https://github.com/brunato/xmlschema/files/2509427/cdpedia2.zip)

**Comment by clarkgflipper** [comment]
I checked again. Probably the problem is rather on the side of XmlSpy being too indifferent to certain violations.

**Comment by brunato** [comment]
Hi,
I haven't examined the correctness of the keyrefs of your schema, but the problem is real. The exception is generated by a wrong reference leaved in *constraints* dictionary of the schema instance. This has to be fixed, probably into the `XsdGlobal.build()` method.

Thanks
