### ISSUE TITLE
recursion loop when using redefine

### ISSUE THREAD

**Issue by jalr** [brunato/xmlschema#99]
I stumbeled upon a recursion loop when using redefine. Maybe it's related to #88?
To make sure its not the fault of my schema files, I've tested it with [these from w3schools.com](https://www.w3schools.com/xml/el_redefine.asp)

This is the traceback when running `xs = xmlschema.XMLSchema('Myschema2.xsd')`:
```
Traceback (most recent call last):
  File "/app/xmlschema/validators/complex_types.py", line 338, in has_simple_content
    return self.content_type.is_simple()
AttributeError: 'XsdGroup' object has no attribute 'is_simple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/xmlschema/validators/complex_types.py", line 338, in has_simple_content
    return self.content_type.is_simple()
AttributeError: 'XsdGroup' object has no attribute 'is_simple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/xmlschema/validators/complex_types.py", line 338, in has_simple_content
    return self.content_type.is_simple()
AttributeError: 'XsdGroup' object has no attribute 'is_simple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    xs = xmlschema.XMLSchema('Myschema2.xsd')
  File "/app/xmlschema/validators/schema.py", line 296, in __init__
    self.maps.build()
  File "/app/xmlschema/validators/globals_.py", line 378, in build
    self.lookup_type(qname)
  File "/app/xmlschema/validators/globals_.py", line 219, in lookup_type
    return lookup_type(self.types, qname, self.validator.TAG_MAP)
  File "/app/xmlschema/validators/globals_.py", line 152, in lookup
    global_map[qname].elem = elem
  File "/app/xmlschema/validators/complex_types.py", line 72, in __setattr__
    super(XsdComplexType, self).__setattr__(name, value)
  File "/app/xmlschema/validators/xsdbase.py", line 201, in __setattr__
    self._parse()
  File "/app/xmlschema/validators/complex_types.py", line 137, in _parse
    self._parse_complex_content_extension(derivation_elem, self.base_type)
  File "/app/xmlschema/validators/complex_types.py", line 280, in _parse_complex_content_extension
    if base_type.is_simple() or base_type.has_simple_content():
  File "/app/xmlschema/validators/complex_types.py", line 343, in has_simple_content
    return self.base_type.is_simple() or self.base_type.has_simple_content()
  File "/app/xmlschema/validators/complex_types.py", line 343, in has_simple_content
    return self.base_type.is_simple() or self.base_type.has_simple_content()
  File "/app/xmlschema/validators/complex_types.py", line 343, in has_simple_content
    return self.base_type.is_simple() or self.base_type.has_simple_content()
  [Previous line repeated 985 more times]
  File "/app/xmlschema/validators/complex_types.py", line 340, in has_simple_content
    if self.content_type or self.content_type.mixed or self.base_type is None:
  File "/app/xmlschema/validators/groups.py", line 314, in __len__
    return len(self._group)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

I've tracked it down a little. This is my diff for debugging it:
```
diff --git a/xmlschema/validators/complex_types.py b/xmlschema/validators/complex_types.py
index b59f5cc..e739061 100644
--- a/xmlschema/validators/complex_types.py
+++ b/xmlschema/validators/complex_types.py
@@ -336,14 +336,16 @@ class XsdComplexType(XsdType, ValidationMixin):
     def has_simple_content(self):
         try:
             return self.content_type.is_simple()
         except AttributeError:
             if self.content_type or self.content_type.mixed or self.base_type is None:
                 return False
             else:
+                if self.base_type == self:
+                    raise RuntimeError('recursion detected, stopping')
                 return self.base_type.is_simple() or self.base_type.has_simple_content()
 
     def has_mixed_content(self):
         try:
             return self.content_type.mixed
         except AttributeError:
             return False

```

**Comment by brunato** [comment]
Hi,
no, it was not related to #88, but to an error in parse methods of XsdComplexType (``_parse_base_type``, ``_parse_complex_content_restriction``, ``_parse_complex_content_extension``). 

Resolved using a local variable for storing the new content type created when apply redefinition. For resolving recursion: in case of a redefinition the base_type refers to itself, so in these cases apply the redefinition but don't set base_type. The fix is available with release v1.0.8.

Thank you for reporting it
